config/routes.rb
Rails.application.routes.draw do


  get '/apropos' => "static_pages#apropos"

  get '/merci' => "static_pages#amerci"
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def apropos
  end

  def merci
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="author" content="">
    <title>Iperamadan</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>

  <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <%= link_to(image_tag("/logo_ipe.png", :alt => "home image", class: "img_logo")) %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Qui sommes nous ?", apropos_path %></li>
              <li><%= button_to "Faire un don", apropos_path, class:"btn btn-primary navbar-btn", :method => :get %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

  <body>
    <%= yield %>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </body>
</html>

app/views/static_pages/apropos.html.erb
<h1>StaticPages#apropos</h1>
<p>Find me in app/views/static_pages/apropos.html.erb</p>

app/views/static_pages/home.html.erb
<!-- Header -->
  <div class="container">
    <div class="row">
      <video width="720" height="405" controls  poster="http://www.supportduweb.com/page/media/videoTag/BigBuckBunny.png">
	<source src="http://www.supportduweb.com/page/media/videoTag/BigBuckBunny.mp4" type="video/mp4">
	<source src="http://www.supportduweb.com/page/media/videoTag/BigBuckBunny.ogg" type="video/ogg">
	<source src="http://www.supportduweb.com/page/media/videoTag/BigBuckBunny.webm" type="video/webm">
	Your browser does not support the video tag or the file format of this video. <a href="http://www.supportduweb.com/">http://www.supportduweb.com/</a>
</video>
    </div>
</div>

app/views/static_pages/merci.html.erb
<h1>StaticPages#merci</h1>
<p>Find me in app/views/static_pages/merci.html.erb</p>